language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
env:
  matrix:
    - SIDEKIQ_VERSION="~> 2.12"
    - SIDEKIQ_VERSION="~> 2.17"
    - SIDEKIQ_VERSION="~> 3.0"
    - SIDEKIQ_VERSION="~> 3.1"
services:
  - redis
